### ISSUE TITLE
How do I even export a spritesheet?

### ISSUE THREAD

**Issue by Fezezen** [agersant/tiger#11]
![image](https://user-images.githubusercontent.com/35386815/190832711-1d20e76b-8975-44d4-bd00-d513500a57ec.png)
I get this error when I try to export my sprite sheet, obviously because I haven't set the metadata template format. But where would I even find out how to make such a template format? I can find no information online on how to use liquid in order to do this, and I certainly cannot find any easily access info on how to do it within your software.
I don't really feel like picking apart the source code just to find out, especially since I don't know Rust.

If it helps, I'm trying to use this for a Monogame project.

Could you please guide me a little bit on how to do this, or at least give me a template that you use?
Thank you.

**Comment by agersant** [comment]
Hello!

First of all I must say I'm amazed that you somehow found out about this project's existence, and even more amazed you chose to try it out. I would **love** to hear your impressions so far and what made you want to try this tool over anything else.

As for your question: there isn't any documentation on the template format, although it is one of the items on the `0.5.0` roadmap. An example template generating `.lua` files can be found [here](https://github.com/agersant/crystal/blob/master/source/crystal.liquid).
Also, [here](https://github.com/agersant/crystal/blob/master/game/arpg/assets/spritesheet/sahagin.lua) is a file generated with said template.

The syntax for the Liquid template language itself has [official documentation](https://shopify.github.io/liquid/). For the exact objects and properties describing the sprite sheet, you'll have to reference the example above. If you're more brave, the source code driving this is [here](https://github.com/agersant/tiger/blob/master/src-tauri/src/export/metadata.rs). Searching for the word `struct` in this file should take you to the few data structures exposed to the template.

**Comment by Fezezen** [comment]
Well thank you. I really like the work you've done. I've been working on a game with some friends on and off for a while and I got around to adding weapons to the game, which naturally needed hurtboxes during animations. I found this project randomly from some ImGui forum I think (I was looking at ImGui stuff for a completely different project of mine), I can't quite remember. It's pretty good and exactly what I needed to make this whole process of importing animations into my game engine with some extra metadata for things like colliders and such. I found it pretty easy to use and the UI is intuitively and nicely laid out.

**Comment by Fezezen** [comment]
Sorry but what exactly do I put in "Metadata Root Directory"?

**Comment by Fezezen** [comment]
Nvm

**Comment by agersant** [comment]
Thank you for the feedback. Let me know if you run into anything else and good luck with your game!
