### ISSUE TITLE
Ability to export the sheet size?

### ISSUE THREAD

**Issue by Terria-K** [agersant/tiger#13]
I really love this tool so much, and a templating system is very cool! However, the only thing that is missing is the ability to export a sheet size. I want my exported file to be minimal as possible, but I cannot do it without the sheet size. I know that this project is in under development but I would appreciate if this can be implemented as well.

**Comment by agersant** [comment]
Thank you for the kind words, I can add this in the next version!

**Comment by agersant** [comment]
Just to make sure I understood correctly, which of the following do you mean?
- Having access to the texture size in the template file
- Manually specifying the texture size in the export settings

**Comment by Terria-K** [comment]
> Just to make sure I understood correctly, which of the following do you mean?
> 
> * Having access to the texture size in the template file
> * Manually specifying the texture size in the export settings

Having an access to the texture size in the template file.

**Comment by agersant** [comment]
Fixed 72f95c3

The `sheet_image` field was replaced by `atlas_image`, which has `.path`, `.width` and `.height` fields.
