### ISSUE TITLE
sheet_image uses backlash instead of forwardslash

### ISSUE THREAD

**Issue by Terria-K** [agersant/tiger#14]
The `sheet_image` path that generated uses backlash instead of forwardslash or double backslash, which is a problem when using json or any format that can make backslash an escaping character.

**Comment by agersant** [comment]
Great catch, also fixing this in version `0.8.0`. In the meantime, you can adjust the paths in your template with `{{ replace sheet_image "\\" "/" }}`.

**Comment by agersant** [comment]
Fixed in 72f95c3

The `sheet_image` field was replaced by `atlas_image`, which has `.path`, `.width` and `.height` fields.
