### ISSUE TITLE
Versions above 0.3.0 do not launch

### ISSUE THREAD

**Issue by Halatnikov** [agersant/tiger#15]
When i click the exe it just flashes for less than a second and immediately closes, i don't know if there's a log file, but i didn't found one

My PC specs:
Windows 10 1904
CPU: Intel Pentium G840 2 cores 2.8ghz
GPU: AMD Radeon HD 6670 1GB
RAM: 6GB

**Comment by Halatnikov** [comment]
I figured out, i had to have Microsoft Edge WebView installed
You might want to specify that in the README

**Comment by agersant** [comment]
Thanks for taking the time to write a report!

The `.msi` installer is supposed to detect this and offer to install Edge WebView, did this not happen for you?

**Comment by Halatnikov** [comment]
nope, it just installed it regularly

**Comment by agersant** [comment]
How strange, I just uninstalled WebView from my computer and the Tiger installer did install it back (without prompting, my mistake on this).
